### PR TITLE
Scroll to new date when it is changed via external props

### LINKED ISSUE #35: Scroll to new date when changed via Props
When the selected date is changed via external props update, it would be nice if the calendar scrolled to the new date.

### PR DESCRIPTION
**Pull request by offsky**
Fixes #35

### CODE REVIEW

**Comment by offsky** [comment]
The CI server appears to be broken.  These tests pass on my machine.

**Comment by clauderic** [comment]
Yeah not sure what's up with that, I'll need to take a look when I get the chance. This looks good to go, merging.

**Comment by georgesboris** [comment]
Is this expected to work with withRange calendars?
Not working for me.

**Comment by clauderic** [comment]
It should, yes. Make sure you always pass a new selected date object when it changes though, otherwise `componentWillReceiveProps` won't be triggered if you're mutating the same object

**Comment by offsky** [comment]
I just tested this again to make sure and it was working for me.

**Comment by bkniffler** [comment]
I suppose this isn't valid anymore? Couldn't find any of this in the current codebase.

**Pull request merged**
