### PR TITLE
fix: Support React 16 (fixes #158)

### LINKED ISSUE #158: Update to React 16
Great calendar by the way, much nicer than some of the alternatives.

I'm using it with React 16 and hoping to remove the npm warnings I get, namely:
`recompose@0.22.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed.`

recompose supports React 16 as of [v0.25.1](https://github.com/acdlite/recompose/releases) so this should be an easy fix.

The `package.json` already allows the React 16 alpha, can this be bumped to the v16.0.0 release? 

I forked the project with the hopes of submitting a pull request with these changes, but after  running `npm install` and `npm start` I get the following error:

```
Failed to compile with 1 error.

 ERROR  in   TypeError: Cannot read property 'request' of undefined
```

### PR DESCRIPTION
**Pull request by SpainTrain**
- Update react peer dep from 16-alpha to 16
- Update recompose dep to react 16 compat version

Closes #158

---
This change is [Reviewable](https://reviewable.io/reviews/clauderic/react-infinite-calendar/177)

### CODE REVIEW

**Comment by i8wu** [comment]
Trying this on React 16.2.0 and it's not working. Getting an error from tiny-virtual-list 
```
TypeError: Cannot read property 'number' of undefined
./node_modules/react-infinite-calendar/node_modules/react-tiny-virtual-list/es/index.js
node_modules/react-infinite-calendar/node_modules/react-tiny-virtual-list/es/index.js:231
  228 | }, _temp2);
  229 | export { VirtualList as default };
  230 | process.env.NODE_ENV !== "production" ? VirtualList.propTypes = {
> 231 |   estimatedItemSize: PropTypes.number,
  232 |   height: PropTypes.number.isRequired,
  233 |   itemCount: PropTypes.number.isRequired,
  234 |   itemSize: PropTypes.oneOfType([PropTypes.number, PropTypes.array, PropTypes.func]).isRequired,
```

**Comment by i8wu** [comment]
Updating react-tiny-virtual-list to the latest version fixed it

**Comment by derekcannon** [comment]
Any update on this PR?

**Comment by stereobooster** [comment]
More recent update https://github.com/clauderic/react-infinite-calendar/pull/197

**Pull request closed without merging**
