### PR TITLE
Added eventType prop to onSelect callback when using withRange()

### LINKED ISSUE #77: onSelect callback when using withRange() should pass an EventType
Currently, when you are selecting a range of dates using the withRange() HOC, the onSelect callback gets called every time the range changes.  When the user clicks the second time to fix the range, the onSelect callback gets called again. There is not currently a way to differentiate between the start click, the end click and all the middle mouse movements.  This is important information that the parent app will need to have. At the minimum, the app needs to know when the user has stopped selecting a range of dates so that it can do whatever expensive processing it needs to do.

I see two ways to do this.

1) Add two additional callbacks `onSelectionStart()` and `onSelectionEnd()` 
2) Add some metadata to the object passed to `onSelect()` to distinguish what type of event it is
```
{
	start: DATE,
	end: DATE,
	selectStart: false,
	isSelecting: true,
	selectEnd: false
}
```

This way, the app can ignore the noise, if it only cares about the final range.

### PR DESCRIPTION
**Pull request by offsky**
Fixes #77

### CODE REVIEW

**Comment by clauderic** [comment]
This is perfect, thank you so much for taking the time to submit this! ❤️

**Comment by offsky** [comment]
Thank you for making range selection possible in the first place! 👍

**Comment by olslash** [comment]
FYI to future googlers (and please correct me if I'm wrong about this), the way to import this constant is:

`import { EVENT_TYPE } from 'react-infinite-calendar/es/Calendar/withRange';`

when i impoted from `react-infinite-calendar/lib/` rather than from `/es/`, my bundle size went up by 35kb, so watch out!

**Comment by clauderic** [comment]
Oh man, good catch. That's definitely an oversight, I'll make sure it's exported by default so you can import it as `import { EVENT_TYPE } from 'react-infinite-calendar`

**Pull request merged**
