### PR TITLE
Handle onClick

### PR DESCRIPTION
**Pull request by slightlytyler**
I ran into the need for this when building a calendar dropdown. I needed to stop the events as to not trigger and event on the parent.

### CODE REVIEW

**Comment by clauderic** [comment]
This is already supported. May need to re-name or update the document, but just use the `beforeSelect` or `onSelect` prop and pass in a function like `function(selectedDate, event) { event.stopPropagation(); }`

**Comment by slightlytyler** [comment]
@clauderic awesome, I'll test it and submit a PR to improve the docs

**Comment by slightlytyler** [comment]
@clauderic I'll test it but I believe that does not cover the case I'm dealing. I need to handle a click *anywhere* on the calendar, not just on a date / year. The `onClick` handler I added is on the root element. Can you please re-open this PR?

**Comment by clauderic** [comment]
Ah... I see. I suppose you could just wrap it with a `div` and add an `onClick` listener for the time being, no?

**Comment by slightlytyler** [comment]
@clauderic ha that totally seems to work, I can't remember exactly why I felt the handler needed to be on the calendar element. oh well, closing this

**Pull request closed without merging**
