### PR TITLE
Date Range Selection

### PR DESCRIPTION
**Pull request by offsky**
Implements date range selection as discussed in issue #4. 

Works with disabledDates and disabledDays. Works with minDate and maxDate. Works with keyboard. Works with header. Works with touch devices.

`<InfiniteCalendar allowRanges={true} selectedDate={today} selectedDateEnd={nextWeek} rangeSelectWithDrag={false}  />`

**allowRanges**: False is default and causes calendar to do the normal behavior.

**rangeSelectWithDrag**: False is default and allows you to select a range by clicking the start and then clicking the end (2 clicks).  By overriding this to true you can have range selection via dragging a range of dates instead.  Because dragging interferes with scrolling on touch devices, it will automatically detect and disable the dragging behavior on touch devices.

### CODE REVIEW

**Comment by offsky** [comment]
These tests don't fail on my machine.  Not sure whats going wrong.

**Comment by clauderic** [comment]
Hey @offsky, spent some time playing with this tonight and it's looking very promising. I've tried to gather my thoughts as best as I could, but It's late and I'm tired, so let me know if anything doesn't make sense :p

In terms of prop names, how would you feel about something along the lines of `rangeSelection={true/false}` and `rangeSelectionBehavior={'hover' / 'drag'}`? I feel like that would be a little more consistent.

Regarding the `selectedDate` / `selectedDateEnd` props, what was the rationale there? It might be a little confusing because one could expect `selectedDateStart` to also be a prop. I'm not sure what the right approach here would be. Perhaps passing in a selectedDate object of shape `{start, end}`?

Finally, in terms of overall look & feel of the range selection, what do you think about something along the lines of:
[range](https://dribbble.com/shots/2098475-Calendar-date-range-picker/attachments/378850)

Regarding the header, I think I'd opt for a horizontal layout instead, similar to the layout in the gif above. This would avoid having to compensate for the height change. Thoughs?

**Comment by offsky** [comment]
I have no problem changing the prop names as you suggested. The reason why I chose "selectedDateEnd" instead of changing the shape of selectedDate was to preserve backwards compatibility. I didn't want to break existing installations of your library and since seletedData can already be set as type "object" there wasn't a clean way to overload that prop. Maybe we can rename "selectedDateEnd" to "rangeSelectionEndDate" to match the other prop name changes?

Horizontal layout of the dates could work too.  I initially tried this, but had problems with smaller responsive sizes wrapping in odd ways. Since I am not a designer and don't know scss well, I thought it better if I didn't tinker in this area.

I ended up doing something like this for my fork. It has a consistent height regardless of 1 date or range selected.  The only problem is that I got rid of the year selection option because I didn't needs this in my project, so Im didn't think you would want this in the pull request.

screen shot 2016-08-01 at 7 54 40 am
screen shot 2016-08-01 at 7 54 53 am

I think it would be better if you redesigned the header, since you have the better design skills and vision.

Would you like me to make those prop name changes?

**Comment by clauderic** [comment]
Sounds good. Do please go ahead with those changes, and I'll try and take a stab at the look & feel as soon as I get the chance.

**Comment by offsky** [comment]
ok, props are renamed and tests pass on my machine

**Comment by jacek213** [comment]
can't wait for this feature to get merged :+1:

**Comment by jacek213** [comment]
any news on merging this feature in?

**Comment by offsky** [comment]
Claudéric, are you waiting for me to improve code coverage?  The missing coverage is on lines related to mouse dragging events (mouseover, mousedown, touchstart) and I wasn't sure how to simulate this in the unit tests.  I'll give it a try if this is what is holding back the pull request.

**Comment by clauderic** [comment]
Hey @offsky, it is something I'd like to be addressed for sure, but it hasn't been what's holding me back. 

There are two main factors that are holding me from merging this at the moment and a couple minor things. First, I do plan to enable custom Day rendering using either child functions or passing in custom components, which is something I think should be taken into account when looking at the current implementation. 

Second, I've taken a first pass at working on styling this to look just like I'd envisioned, but so far it's proven to be a tricky process / bumpy road. I'll let you know as soon as I have something I'm satisfied with on that front.

In terms of functionality, there is one element that I think should be revised, though this is a minor change. I don't think you should be able to select dates backwards (in the past) once a start date is selected. It forces the header to change the selected start-date and it doesn't feel like a common use-case.

**Comment by offsky** [comment]
Ok, I'll see if I can work on the unit tests, but I may need a little help. Is there a way to contact you off of github?

Regarding the backwards selection: I think you are assuming that people always choose the start-date first. In my application (a to-do list) this isn't the case, people usually pick the due-date first and then drag backwards to set the start-date. I think it would be better if you could select the range in either direction, and the calendar intelligently figures it out. I already have code in place to flip the dates if start>end. If you really want, we could make this a prop.

**Comment by clauderic** [comment]
Hey @offsky, my contact info is in my profile, happy to help out in any way you need. Alternatively, I'm also on Gitter.

I see. I still think it feels a little quirky, but I'd be okay with making this a configurable option. Perhaps we can disable header animation for those date changes so it's a little smoother.

**Comment by jacek213** [comment]
@clauderic I see that all tests are passing now, when can we expect it to be merged in?

**Comment by clauderic** [comment]
@jacek213 The simple answer is: When it is ready.

Just because the tests are passing does not mean it is ready to be merged, and once it is merged, I'm the one who will have to support it. 

If you have a time sensitive need for this, NPM makes it very simple to install directly from @offsky's fork, and you can get started using it right away.

Open source maintainers have limited time and resources, and I am no exception. Please have take a minute to read https://github.com/turbolinks/turbolinks/pull/124#issuecomment-239826060 before asking again. Instead, why not ask "how can I help move this forward" next time you feel strongly about a PR.

**Comment by jacek213** [comment]
@clauderic thank you for the feedback, I didn't mean to be offensive. However I haven't seen any news on the topic for over 2 weeks, therefore I thought it wouldn't hurt to ask about the current progress, because as you've noticed - I do have a time sensitive need for this feature. If there are certain things which need to be done and would help to push it forward - let me know and I might submit a PR.

**Comment by nickcan** [comment]
@clauderic @offsky I've implemented this calendar into a project at work and there is a new need for it to have range selection. Our team doesn't feel comfortable using forked libraries as it may have future consequences.

Is there anything I can do to help move this along (code, tests, docs)? What is the assuredness that this PR will be merged in the future?

**Comment by clauderic** [comment]
Hey everyone,

Finally had some free time over the weekend and was able to spend a bit of time working on this. I've finally arrived at something that I'm fairly satisfied with visually, though it's going to require a few code changes to implement. I wanted something that would both look good and be simple to use, while still being easy to skin. This is where I landed:

screen shot 2016-10-16 at 2 01 53 pm

@nickcan, first off, thanks for offering to help move this forward 👍 I can't make any promises in terms of _when_ this PR will be merged, as I have limited bandwidth at the moment, but I believe it's safe to say that this will eventually make it's way back into master :)

**Comment by clauderic** [comment]
@offsky I've implemented the new look & feel for the selection range, would you mind giving me editing rights to your PR?

**Comment by offsky** [comment]
I like the design you have settled on. I have given you permission to edit this PR.  Thanks!

**Comment by nickcan** [comment]
@clauderic and @offsky I created a fork off of @offsky's fork and implemented the design proposed above.

https://github.com/Toodledo/react-infinite-calendar/pull/1

**Comment by olslash** [comment]
bump to say that at least one guy out there (me) still wants to see this happen!

**Comment by renet** [comment]
+1 from me for this pull request.

**Comment by neekey** [comment]
+1 for this pull request!

**Comment by renet** [comment]
The calendar has such a stylish modern design, but the date range highlight looks pretty old-fashioned. It doesn't really fit into the calendars design. Would you mind reworking this, before merging, please? :)

**Comment by clauderic** [comment]
Yeah I'm still not fully satisfied with the look & feel of the range selection either, I'm absolutely open to suggestions if you'd like to take a stab at it or have examples you like

**Comment by renet** [comment]
I might give this a try, but I don't have much time lately. I like the style in your animated gif example. Would you rather use a style like that, or a different one?

**Comment by dsbl411** [comment]
Hi,

How about something like that?

proposal5

**Comment by clauderic** [comment]
Hey all! Exciting news: I just published `react-infinite-calendar` Version 2.0, which comes with date-range selection out of the box  🎉

 Check out the updated demo site to play with it: http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/range-selection

*Disclaimer: It's still experimental and there are a few bugs to iron out on mobile, but PRs are welcome to make it better!*

Here's the final look & feel I settled on (thanks for the inspiration @dsbl411!):

screen shot 2017-02-24 at 10 00 26 pm


I decided to take an entirely different approach from this PR in terms of implementation and chose to take the higher-order component approach to solving this problem. What does that look like in practice? `react-infinite-calendar` now ships with a few HOCs that you can use to enhance the default functionality (or, if your use-case isn't supported out of the box, you can even create your own). Usage is as follows:

```jsx
import React from 'react';
import {render} from 'react-dom';
import InfiniteCalendar, {
  Calendar,
  withRange,
} from 'react-infinite-calendar';
import 'react-infinite-calendar/styles.css';

render(
  <InfiniteCalendar
    Component={withRange(Calendar)}
    selected={{
      start: new Date(2017, 1, 10),
      end: new Date(2017, 1, 18),
    }}
  />,
  document.querySelector('#root')
);
```

Thanks everyone for your patience and for your input on this PR. And a very special thanks to @offsky for all the efforts you put into this PR, it helped put me on the right track ❤️!

**Pull request closed without merging**
